# Generated by Django 2.1.2 on 2018-10-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_login_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(db_index=True, default='LjSrbrPvb', max_length=9, verbose_name='uid'),
        ),
    ]
